#!/bin/bash
git config --global user.email "game.master.habib@gmail.com"
sleep 2
git config --global user.name "GMhabib"
sleep 2
git init
sleep 2
git config --global safe.directory /data/data/com.termux/files/home/website_youtube/
sleep 2
 git add *
 sleep 2
 git commit -m "youtube baru saya"
 sleep 2
 clear
 sleep 10
 git remote add origin https://github.com/GMhabib/vps_youtube.git && git branch -M main && git push -u origin main
